version: "3.8"
services:
  db:
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    volumes:
      - ./db/ddl/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/dml/load_data_scripts.sql:/docker-entrypoint-initdb.d/load_data_scripts.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    restart: always